//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace timbradoLayoutCSharp.WSLayoutFacturacionModerna {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://t2demo.facturacionmoderna.com/timbrado/soap", ConfigurationName="WSLayoutFacturacionModerna.Timbrado_ManagerPort")]
    public interface Timbrado_ManagerPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2demo.facturacionmoderna.com/timbrado/soap#requestTimbrarCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object requestTimbrarCFDI(requestTimbrarCFDI request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2demo.facturacionmoderna.com/timbrado/soap#requestCancelarCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string requestCancelarCFDI(requestCancelarCFDI request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Timbrado_ManagerPortChannel : timbradoLayoutCSharp.WSLayoutFacturacionModerna.Timbrado_ManagerPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Timbrado_ManagerPortClient : System.ServiceModel.ClientBase<timbradoLayoutCSharp.WSLayoutFacturacionModerna.Timbrado_ManagerPort>, timbradoLayoutCSharp.WSLayoutFacturacionModerna.Timbrado_ManagerPort {
        
        public Timbrado_ManagerPortClient() {
        }
        
        public Timbrado_ManagerPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Timbrado_ManagerPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Timbrado_ManagerPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Timbrado_ManagerPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object requestTimbrarCFDI(requestTimbrarCFDI request) {            
            try {
                return base.Channel.requestTimbrarCFDI(request);
            }
            catch (System.ServiceModel.FaultException soapFault)
            { //-->>Manejo de soapFault
                Console.WriteLine("[" + soapFault.Code.Name + "] " + soapFault.Message);
                Object objResponse = new Object();
                objResponse = null;
                return objResponse;
            }            
        }
        
        public string requestCancelarCFDI(requestCancelarCFDI request) {
            try
            {
                return base.Channel.requestCancelarCFDI(request); 
            }
            catch (System.ServiceModel.FaultException soapFault)
            { //-->>Manejo de soapFault
                Console.WriteLine("["+soapFault.Code.Name+"] "+soapFault.Message);
                return "";
            }
            
        }
    }
}
