//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace WSConecFM.WSLayoutFacturacionModerna {
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="WSLayoutFacturacionModerna.Timbrado_ManagerPort")]
    public interface Timbrado_ManagerPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object requestTimbrarCFDI(requestTimbrarCFDI request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object requestCancelarCFDI(requestCancelarCFDI request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Timbrado_ManagerPortChannel : WSConecFM.WSLayoutFacturacionModerna.Timbrado_ManagerPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Timbrado_ManagerPortClient : System.ServiceModel.ClientBase<WSConecFM.WSLayoutFacturacionModerna.Timbrado_ManagerPort>, WSConecFM.WSLayoutFacturacionModerna.Timbrado_ManagerPort {
        
        public Timbrado_ManagerPortClient() {
        }
        
        public Timbrado_ManagerPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Timbrado_ManagerPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Timbrado_ManagerPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Timbrado_ManagerPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object requestTimbrarCFDI(requestTimbrarCFDI request) {
			//try {
                return base.Channel.requestTimbrarCFDI(request);
            //}
            //catch (System.ServiceModel.FaultException soapFault)
            //{ //-->>Manejo de soapFault
            //    Console.WriteLine("[" + soapFault.Code.Name + "] " + soapFault.Message);
            //    Object objResponse = new Object();
            //    objResponse = null;
            //    return objResponse;
            //}	
        }
        
        public object requestCancelarCFDI(requestCancelarCFDI request) {
            //try
            //{
                return base.Channel.requestCancelarCFDI(request); 
            //}
            //catch (System.ServiceModel.FaultException soapFault)
            //{ //-->>Manejo de soapFault
            //    Console.WriteLine("["+soapFault.Code.Name+"] "+soapFault.Message);
            //    return "";
            //}
			
        }
    }
}
